# Generated by Django 3.2.5 on 2021-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='vegetarian'),
        ),
    ]
