version: '3.8'

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=emenu
      - POSTGRES_USER=emenu
      - POSTGRES_PASSWORD=pass
      - TZ='GMT+2'
      - PGTZ='GMT+2'
    volumes:
      - ./db:/docker-entrypoint-initdb.dt/
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  emenu:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/emenu/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A emenu worker -l info
    volumes:
      - .:/usr/src/emenu/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=emenu
      - POSTGRES_USER=emenu
      - POSTGRES_PASSWORD=pass
      - TZ='GMT+2'
      - PGTZ='GMT+2'
    depends_on:
      - db
      - emenu
      - redis
  celery-beat:
    build: .
    command: celery -A emenu beat -l info
    volumes:
      - .:/usr/src/emenu/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=emenu
      - POSTGRES_USER=emenu
      - POSTGRES_PASSWORD=pass
      - TZ='GMT+2'
      - PGTZ='GMT+2'
    depends_on:
      - db
      - emenu
      - redis
